### ISSUE TITLE
Home Assistant instable because of this integration 

### ISSUE THREAD

**Issue by smarthomejunkie** [crownstone/crownstone-home-assistant#4] opened 2020-12-24 22:33 UTC
I tested this integration thoroughly, but it turned out that my Home Assistant instance got very instable because of it. The system became slow and sometimes unresponsive. After I removed the crownstone integration my HA insurance became stable again. 

Not sure what the exact reason in this code is, but after installing this integration the problem was gone.

**Comment by mrquincle** [comment] 2020-12-24 23:09
Hence, it becomes unstable, but reinstallation solves the problem? 

Do you know a version? 

And is the system running stable now?

**Comment by RicArch97** [comment] 2020-12-28 15:24
Are you using a Crownstone USB dongle?

**Comment by smarthomejunkie** [comment] 2021-02-06 11:32
Sorry heren,
Veelte late reactie natuurlijk! Ik heb de Crownstone integratie een tijdje
uit mijn systeem gehaald en heb hem deze ochtend opnieuw geïnstalleerd. Tot
op dit moment merk ik nog geen instabiliteit in mijn systeem. Ik houd
jullie op de hoogte.

Groet,
Ed

**Comment by mrquincle** [comment] 2021-03-08 08:31
Hi @smarthomejunkie. Did you experience problem since you reported this problem? Otherwise we can better close this issue I think (without the ability to be able to reproduce this problem).

**Closed as completed** 2021-09-03 15:59 UTC
