### ISSUE TITLE
Automation based on presence can't be created

### ISSUE THREAD

**Issue by ddcbe** [crownstone/crownstone-home-assistant#7] opened 2022-01-16 20:13 UTC
I'm running HA 2021.12.9  and want to create an automation based on the presence in a specific room. When I want to add this automation, I don't get the possibility to create such and automation. When starting an automation from scratch, I can't select any trigger.

**Comment by vliedel** [comment] 2022-01-17 12:18
Hi, I don't know too much about the HA integration, but a quick check: is the localization working in the crownstone phone app?

**Comment by mrquincle** [comment] 2022-01-17 13:32
@ddcbe Are you talking about Crownstone as in Home Assistant core, or as in HACS?

https://github.com/crownstone/crownstone-home-assistant

> Crownstone Home Assistant integration beta to test new features before they are integrated into the core version.
> 
> The Crownstone integration is available in Home Assistant core since version 2021.10.0. It is however limited in features and only supports switching and dimming Crownstones for now. With time, features will be migrated from this version to the core version.

If presence automation doesn't work in HACS, please come back to us. Otherwise, please install the HACS version to get the full functionality.

**Comment by ddcbe** [comment] 2022-01-17 18:48
Hi, I'm using the beta (v2.0.3) from HACS. Localization is working fine both in the phone app and in Home Assistance. I can see the correct in-home location in home assistance. The only thing I'm currently missing is  presence automation. I did have some rules created by the phone app. Would that prevent creation presence automation from HACS?

**Comment by mrquincle** [comment] 2022-01-18 08:42
I don't think that should be the case.

@RicArch97 Perhaps you can enlighten us. :-)

**Comment by RicArch97** [comment] 2022-01-18 14:01
Hi, this **should** indeed be working.

I have however not touched the beta version in some time, so it may be possible that there are regressions caused by new HA updates. I run the (official) core version on my personal HA instance so it's not something i could have stumbled upon myself this time around :)

I'll do some testing on this version again to see what's going on, thanks for your report!

**Comment by ddcbe** [comment] 2022-01-19 20:53
Thanks! Let me know if you need any additional information to help you with this.

**Comment by RicArch97** [comment] 2022-01-23 14:29
Fixed in version 2.0.4

**Closed as completed by RicArch97** 2022-01-23 14:29 UTC

**Comment by ddcbe** [comment] 2022-01-23 18:55
Thanks! This works now!
